### ISSUE TITLE
1.0.3 crash with Quiverbow

### ISSUE THREAD

**Issue by dirtyfargo** [blay09/CraftingCraft#1]
Description: Crash when opening up the inventory of the Stone Crafting Table, the Crafting Table Frame, or the Nether Crafting table. Quiverbow must be present to replicate the issue.
Quiverbow version: b100
CraftingCraft version: 1.0.3
Crash Report: https://gist.github.com/69041189dc0993fc480c

**Comment by blay09** [comment]
This is an issue on Quiverbow's side. They're trying to access a slot that doesn't exist ("tenth" slot in the crafting grid). The default crafting inventory has a check to prevent the crash from happening, but that's dumb and unnecessary as long as people use it correctly.

I'm going to add the failcheck to my code, but you should really bring this to the Quiverbow devs to get it fixed there. They shouldn't rely on people doing bounds checks, especially when they already know the inventory is only nine slots big.

**Comment by dirtyfargo** [comment]
Just found a newer version of Quiverbow (101b), but I still get the same crash with CraftingCraft 1.0.3. So yeap I will report it to them thanks =)

**Comment by dirtyfargo** [comment]
It has been reported to Quiverbow and will be fixed on their next update :)
